const jwt = require('jsonwebtoken'); // Evaluates cryptographic tokens issued during the login process
const User = require('../models/User'); // References the database schema to validate account existence

/*
    Standard Authentication Middleware
    Purpose: Intercepts network requests to protected routes, ensuring the user possesses a valid JSON Web Token.
    Mechanism: If the token is valid, it retrieves the full user profile from the database and attaches it to the request object, allowing downstream controllers to access the user's data seamlessly.
*/
const requireAuth = (req, res, next) => {
    const token = req.cookies.jwt; // Extracts the token specifically from the HTTP-only cookie store

    if (token) {
        // Cryptographically verifies that the token was generated by our server and has not expired
        jwt.verify(token, process.env.JWT_SECRET, async (err, decodedToken) => {
            if (err) {
                res.redirect('/login'); // Expels users with tampered or expired tokens
            } else {
                try {
                    // Rehydrates the session by fetching the complete user record based on the ID embedded inside the token payload
                    const user = await User.findById(decodedToken.id);
                    req.user = user; // Binds the record to the request cycle
                    next(); // Authorizes the request to proceed to the intended controller function
                } catch (error) {
                    console.error("Middleware DB Error:", error);
                    res.redirect('/login');
                }
            }
        });
    } else {
        // Distinguishes between browser navigation requests (redirects) and background AJAX requests (JSON error)
        if (req.originalUrl.startsWith('/api/')) {
            return res.status(401).json({ success: false, message: 'You must be logged in.' });
        }
        res.redirect('/login');
    }
};

/*
    Administrative Authorization Middleware
    Purpose: Enforces Role-Based Access Control (RBAC) to protect sensitive management endpoints.
    Mechanism: Operates identically to standard authentication but explicitly requires the token payload to contain an 'admin' role flag before permitting access.
*/
const requireAdmin = (req, res, next) => {
    const token = req.cookies.jwt;

    if (token) {
        jwt.verify(token, process.env.JWT_SECRET, async (err, decodedToken) => {
            // Evaluates both the mathematical validity of the token and the strict string value of the role
            if (err || decodedToken.role !== 'admin') {
                res.redirect('/'); // Downgrades standard users back to the public interface
            } else {
                try {
                    const user = await User.findById(decodedToken.id);
                    req.user = user;
                    next(); // Authorizes access to the admin controller
                } catch (error) {
                    res.redirect('/login');
                }
            }
        });
    } else {
        res.redirect('/login');
    }
};

module.exports = {
    requireAuth,
    requireAdmin
};